services:
  server:
    env_file: .env
    container_name: wasm-server
    build:
      context: ./server
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./server
          target: /var/www/html
          ignore:
            - vendor/
    ports:
      - "8000:${SERVER_PORT}"
      - "5173:5173"
      - "8181:80"
    volumes:
      - ./server:/var/www/html
    tty: true
    depends_on:
      - postgres

  postgres:
    env_file: .env
    image: postgres:17
    container_name: wasm-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:${POSTGRES_POST}"
    volumes:
      - ./server/migrate:/docker-entrypoint-initdb.d
      - ./server/postgres/data:/var/lib/postgresql/data
      - ./server/postgres/backups:/backups

  adminer:
    env_file: .env
    image: adminer
    container_name: wasm-adminer
    ports:
      - "8080:${ADMINER_PORT}"
    depends_on:
      - postgres

  # frontend:
  #   env_file: .env
  #   profiles: [do_not_start]
  #   container_name: wasm-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4123:${FRONTEND_PORT}"
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     - VITE_SERVER_URL=http://localhost:${SERVER_PORT}
  #     - BROWSER=none
  #   depends_on:
  #     - server
  #   command: npm run dev
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./frontend
  #         target: /app
  #         initial_sync: true
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: package.json
